version: 1.0.{build}

image:
- Visual Studio 2019
- Visual Studio 2017

configuration:
- Release

# environment:
#   matrix:

clone_depth: 2

before_build:
- cmd: git submodule update --init --recursive
- cmd: cmake -H. -Bbuild

build:
  verbosity: normal