version: 1.0.{build}

image:
- Visual Studio 2019
- Ubuntu

configuration:
- Release

before_build:
- git submodule update --init --recursive
- cmake -H. -Bbuild -DCMAKE_CONFIGURATION_TYPES=Release -DCMAKE_BUILD_TYPE=Release

build_script:
- cd build
- cmake --build --config Release --target Marble.Runtime.CoreLib

build:
  verbosity: normal