version: 1.0.{build}

image:
- Visual Studio 2019
- Ubuntu

configuration:
- Release

before_build:
- cmd: git submodule update --init --recursive
- cmd: cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release

build_script:
- cmd: cd build
- cmd: cmake --build --config Release

build:
  verbosity: normal